repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.1.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-docstring-first
        -   id: check-yaml
        -   id: debug-statements
        -   id: double-quote-string-fixer
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.7
        hooks:
        -   id: flake8
    -   repo: meta
        hooks:
        -   id: check-hooks-apply
        -   id: check-useless-excludes

    -   repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.5.1
        hooks:
        -   id: python-check-blanket-noqa
