# Generated by Django 2.2.13 on 2020-11-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_year_of_play', models.DateField()),
                ('most_recent_team_id', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('first_year_of_play', models.DateField()),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_city', models.CharField(max_length=100)),
                ('venue_tz_id', models.CharField(max_length=100)),
                ('venue_tz_offset', models.IntegerField()),
                ('venue_tz_name', models.CharField(max_length=10)),
                ('team_short_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Conference')),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Division')),
                ('franchise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Franchise')),
            ],
        ),
    ]
